name: build-android-app

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" , "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
          - run: fastlane android deploy_beta
    