name: build-android-app

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" , "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: initialize gradle
      run: gradle init
    - name: config proj
      run: |
          echo "$MY_SECRET" >> app/smile_config.json
          cat app/smile_config.json
          echo "$KEY_STORE" >> app/app_keystore.keystore
          cat app/app_keystore.keystore
      shell: bash
      env:
        MY_SECRET: ${{secrets.SMILE_CONFIG}}
        KEY_STORE: ${{secrets.KEY_STORE}}
        SID_keyAlias: '${{secrets.SID_KEYALIAS}}'
        SID_keyPassword: '${{secrets.SID_KEYPASSWORD}}'
        SID_storePassword: '${{secrets.SID_STOREPASSWORD}}'
    - run: fastlane android deploy_beta
    