name: build-android-app

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" , "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: initialize gradle
      run: gradle init
    - name: config proj
      run: |
          echo "$MY_SECRET" >> app/smile_config.json
          cat app/smile_config.json
          echo "$KEY_STORE" >> app/app_keystore.keystore
          cat app/app_keystore.keystore
          echo SID_keyAlias=\"$SID_keyAlias\" >> ./secrets.properties
          echo SID_keyPassword=\"$SID_keyPassword\" >> ./secrets.properties
          echo SID_storePassword=\"$SID_storePassword\" >> ./secrets.properties
          echo SID_KEYSTORE=\"$SID_KEYSTORE\" >> ./secrets.properties
          cat ./secrets.properties
          echo SID_AWS_ACCESS_KEY_ID=\"$SID_AWS_ACCESS_KEY_ID\" >> .fastlane/secrets.json
          echo SID_AWS_SECRET_ACCESS_KEY=\"$SID_AWS_SECRET_ACCESS_KEY\" >> .fastlane/secrets.json
          echo SID_AWS_BUCKET=\"$SID_AWS_BUCKET\" >> .fastlane/secrets.json
          echo SID_AWS_REGION=\"$SID_AWS_REGION\" >> .fastlane/secrets.json
          cat .fastlane/secrets.json
      shell: bash
      env:
        MY_SECRET: ${{secrets.SMILE_CONFIG}}
        KEY_STORE: ${{secrets.KEY_STORE}}
        SID_keyAlias: ${{secrets.SID_KEYALIAS}}
        SID_keyPassword: ${{secrets.SID_KEYPASSWORD}}
        SID_storePassword: ${{secrets.SID_STOREPASSWORD}}
        SID_KEYSTORE: ${{secrets.SID_KEYSTORE}}
        SID_AWS_ACCESS_KEY_ID: ${{secrets.SID_AWS_ACCESS_KEY_ID}}
        SID_AWS_SECRET_ACCESS_KEY: ${{secrets.SID_AWS_SECRET_ACCESS_KEY}}
        SID_AWS_BUCKET: ${{secrets.SID_AWS_BUCKET}}
        SID_AWS_REGION: ${{secrets.SID_AWS_REGION}}
    - run: fastlane android deploy_beta
    