name: build-android-manually

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 10
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: initialize gradle
      run: gradle init
    - name: Create secret-file.txt from B64_SECRET1
      run: |
        $secretFile = Join-Path -Path $env:RUNNER_TEMP -ChildPath "smile_config.json";
        $encodedBytes = [System.Convert]::FromBase64String($env:SECRET_DATA1);
        Set-Content $secretFile -Value $encodedBytes -AsByteStream;
        $secretFileHash = Get-FileHash $secretFile;
        echo "SECRET_FILE=$secretFile" >> $GITHUB_ENV
        echo "SECRET_FILE_HASH=$($secretFileHash.Hash)" >> $GITHUB_ENV
        Write-Host "Secret file $secretFile has hash $($secretFileHash.Hash)";
      shell: pwsh
      env:
        SECRET_DATA1: ${{ secrets.B64_SECRET1 }}
    - name: Delete secret file
      run: Remove-Item -Path $env:SECRET_FILE;
      shell: pwsh
      if: always()
      env:
        SECRET_FILE: ${{ env.SECRET_FILE }}
    - run: fastlane android deploy_beta
